<?php return function ($fontDir, $rootDir) {
return array (
  'sans-serif' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold' => $rootDir . '/lib/fonts/ZapfDingbats',
    'italic' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold_italic' => $rootDir . '/lib/fonts/ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $rootDir . '/lib/fonts/Symbol',
    'bold' => $rootDir . '/lib/fonts/Symbol',
    'italic' => $rootDir . '/lib/fonts/Symbol',
    'bold_italic' => $rootDir . '/lib/fonts/Symbol',
  ),
  'serif' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSans-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSans-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSans-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSansMono-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSansMono-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSansMono-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSerif-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSerif-BoldItalic',
    'italic' => $rootDir . '/lib/fonts/DejaVuSerif-Italic',
    'normal' => $rootDir . '/lib/fonts/DejaVuSerif',
  ),
  'be vietnam pro' => array(
    '100_italic' => $fontDir . '/be_vietnam_pro_100_italic_29779e26d71df803b435442710575e72',
    '200_italic' => $fontDir . '/be_vietnam_pro_200_italic_16fbe58e1e5d2038f154c9e6fb0a3b66',
    '300_italic' => $fontDir . '/be_vietnam_pro_300_italic_dc977d179b44f3d12819f44cd149cfa0',
    'italic' => $fontDir . '/be_vietnam_pro_italic_c7e1f7f0d2124ebb1fb6966019ab52e6',
    '500_italic' => $fontDir . '/be_vietnam_pro_500_italic_5a3fd426fc1089d7580126d8a7e97b1a',
    '600_italic' => $fontDir . '/be_vietnam_pro_600_italic_4c8f622c44240b5d6547260bfe53d884',
    'bold_italic' => $fontDir . '/be_vietnam_pro_bold_italic_15de800e97bee3989eabd214a670da42',
    '800_italic' => $fontDir . '/be_vietnam_pro_800_italic_a8c2b143856f19b34c72063db5217e4f',
    '900_italic' => $fontDir . '/be_vietnam_pro_900_italic_4183ae045e5a6ed7f1a9930c2696eaf4',
    '100' => $fontDir . '/be_vietnam_pro_100_0243465743b35d27ce6b64f9c2ac981e',
    '200' => $fontDir . '/be_vietnam_pro_200_a933a944c826b28b1c2d82505e6beaa9',
    '300' => $fontDir . '/be_vietnam_pro_300_4d44fc5b7ab672399a653821b7424e6a',
    'normal' => $fontDir . '/be_vietnam_pro_normal_14656a2f79212919d1a27b63a72565f3',
    '500' => $fontDir . '/be_vietnam_pro_500_e30210c933188ca5ef7c5075bcb35164',
    '600' => $fontDir . '/be_vietnam_pro_600_fdea5881b7a20f51875c84d566b6d634',
    'bold' => $fontDir . '/be_vietnam_pro_bold_0901744c213fcea1985fbbd05164d28e',
    '800' => $fontDir . '/be_vietnam_pro_800_6f09adcdaba11c2d7d03fa8ffa62d8fa',
    '900' => $fontDir . '/be_vietnam_pro_900_c8f0dbe96a0e3b6bfcd5e279907ddfd9',
  ),
);
}; ?>